# Generated by Django 3.2 on 2021-05-05 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('programming_tools', models.CharField(max_length=50, verbose_name='编程工具')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('english_title', models.CharField(max_length=50, verbose_name='英文标题')),
                ('classify', models.CharField(max_length=50, verbose_name='内容分类')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255, verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.article', verbose_name='评论文章')),
            ],
        ),
    ]
